# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c60b5ad31f7c089e819f6b3b2736106b0e8486e8410c71d7cc72236e30804ba5051a58c43dbc3d3f1e3133d31311ef2a5831acd2eb17d61b3911d5531f3438

test:
  secret_key_base: 6dc14adf38df96fc50d8d6c74998206d0b3db284b9c694ebef9d16a8760e3c8bb56532ceef8f4630aa3e5f15bf7587e72bd4e7608b2196daeb5db169b916fca5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
